const state={cash:10000000,crew:'바이브 크루',selected:0,portfolio:1248000};
const stocks=[
{name:'승화',ticker:'SHWA',goal:'창업 프로젝트',price:128, fv:142, chg:8.6, emoji:'🚀', color:'#3182f6', reason:'실행 난이도 높고 목표 정렬도가 매우 높아 AI 적정가가 시장가보다 높게 산정됐어.'},
{name:'민준',ticker:'MJUN',goal:'운동 루틴',price:94, fv:88, chg:-3.2, emoji:'🏋️', color:'#16a34a', reason:'최근 인증 공백이 있어 FV가 점진 감쇠 중이야. 자발 halt는 아니어서 경고 관찰 상태.'},
{name:'다원',ticker:'DAWN',goal:'디자인 포트폴리오',price:117, fv:121, chg:5.1, emoji:'🎨', color:'#7c3aed', reason:'연속 작업 인증과 크루 평가가 좋아 시장가와 FV가 함께 상승 중이야.'},
{name:'지후',ticker:'JHOO',goal:'시험 공부',price:83, fv:97, chg:1.4, emoji:'📚', color:'#f59e0b', reason:'목표 정렬도는 높지만 난이도 자기신고와 AI 기준선 차이가 있어 일부 보류됐어.'}
];
let news=[
{type:'good',title:'[공시] 승화, 기능명세 v5 확정',body:'창업 프로젝트 섹터에 강한 호재. AI는 목표 정렬도 96점을 부여했다. 예상 FV +6.4%'},
{type:'bad',title:'[속보] 민준, 이틀 연속 운동 인증 누락',body:'체력 섹터 신뢰도 약화. 단, 폭락 대신 점진 감쇠 룰이 적용된다. 예상 FV -2.8%'},
{type:'neutral',title:'[분석] 다원, 포트폴리오 리뉴얼 예고',body:'TMI성 뉴스로 FV에는 미반영. 다만 크루 심리로 단기 시장가 변동 가능.'}
];
function krw(n){return '₩'+Math.round(n).toLocaleString('ko-KR')}
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='home')renderHome();if(id==='news')renderNews();if(id==='leaderboard')renderRank();}
function startCrew(){state.crew=document.getElementById('crewNameInput').value||'바이브 크루';stocks[0].name=document.getElementById('myName').value||'승화';stocks[0].goal=document.getElementById('myGoal').value;document.getElementById('crewTitle').textContent=state.crew;go('home')}
function renderHome(){document.getElementById('cash').textContent=krw(state.cash);document.getElementById('portfolioValue').textContent=krw(state.portfolio);document.getElementById('headline').innerHTML=`${news[0].title}<br><span style="color:#cbd5e1;font-size:13px">${news[0].body}</span>`;document.getElementById('stockList').innerHTML=stocks.map((s,i)=>`<button class="stock-item" onclick="openStock(${i})"><div class="avatar" style="background:${s.color}">${s.emoji}</div><div class="stock-main"><b>${s.name} 주식</b><span>${s.ticker} · ${s.goal}</span></div><div class="stock-price"><b>${s.price.toFixed(0)}</b><span class="${s.chg>=0?'up':'down'}">${s.chg>=0?'+':''}${s.chg}%</span></div></button>`).join('')}
function openStock(i){state.selected=i;const s=stocks[i];document.getElementById('detailName').textContent=s.name+' 주식';document.getElementById('marketPrice').textContent=s.price.toFixed(0);document.getElementById('fvPrice').textContent=s.fv.toFixed(0);const gap=s.fv-s.price;document.getElementById('priceGap').textContent=gap>=0?`AI 기준 ${gap.toFixed(0)} 저평가 · 매수 관심`:`AI 기준 ${Math.abs(gap).toFixed(0)} 고평가 · 관망 필요`;document.getElementById('aiReason').innerHTML=`<h3>AI 판단 근거</h3><p>${s.reason}</p>`;drawChart(s);document.getElementById('betResult').textContent='';go('detail')}
function drawChart(s){const points=[40,70,62,90,85,115,105,130].map((y,i)=>`${20+i*40},${150-y}`).join(' ');document.getElementById('chart').innerHTML=`<defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="${s.color}"/><stop offset="1" stop-color="#22c55e"/></linearGradient></defs><polyline points="${points}" fill="none" stroke="url(#g)" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><line x1="20" y1="${150-s.fv}" x2="300" y2="${150-s.fv}" stroke="#94a3b8" stroke-dasharray="6 6"/><text x="22" y="${145-s.fv}" font-size="11" fill="#64748b">FV</text>`}
function trade(type){const s=stocks[state.selected];const cost=s.price*10000;if(type==='buy'){state.cash-=cost;state.portfolio+=cost;s.price*=1.015}else{state.cash+=cost;state.portfolio-=cost;s.price*=0.985}openStock(state.selected)}
function bet(side){const s=stocks[state.selected];document.getElementById('betResult').textContent=`${s.name}의 내일을 ${side==='long'?'LONG':'SHORT'}으로 예측했어. 베팅금 5만원 mock 체결.`}
function submitProof(){const diff=+document.getElementById('difficulty').value;const imp=+document.getElementById('importance').value;const score=diff*imp;const impact=Math.min(12,(score/25*10)).toFixed(1);document.getElementById('proofResult').innerHTML=`<b>AI 판정: 호재 +${impact}%</b><p>난이도 ${diff}/5, 경중 ${imp}/5. 목표 정렬도가 높아 오늘 종가 FV에 반영 예정.</p>`;news.unshift({type:'good',title:'[공시] '+stocks[0].name+', 오늘 실적 인증 완료',body:`난이도×경중 점수 ${score}/25. 펀더멘털 강화로 FV +${impact}% 예상.`});stocks[0].fv*=1+impact/100;stocks[0].chg+=Number(impact)/2;}
function renderNews(){document.getElementById('newsFeed').innerHTML=news.map(n=>`<article class="news-card"><span class="tag ${n.type}">${n.type==='good'?'호재':n.type==='bad'?'악재':'중립'}</span><h3>${n.title}</h3><p>${n.body}</p></article>`).join('')}
function renderRank(){const sorted=[...stocks].sort((a,b)=>b.chg-a.chg);document.getElementById('rankList').innerHTML=sorted.map((s,i)=>`<div class="stock-item"><div class="avatar" style="background:${s.color}">${i+1}</div><div class="stock-main"><b>${s.name}</b><span>${s.goal}</span></div><div class="stock-price"><b>${s.price.toFixed(0)}</b><span class="${s.chg>=0?'up':'down'}">${s.chg>=0?'+':''}${s.chg.toFixed(1)}%</span></div></div>`).join('')}
renderHome();