const state={cash:10000000,crew:'바이브 크루',selected:0,portfolio:1248000,commentTag:'응원',latestDisclosure:null};
const stocks=[
{name:'승화',ticker:'SHWA',goal:'창업 프로젝트',price:128,fv:142,chg:8.6,emoji:'🚀',color:'#3182f6',proofsToday:2,strikes:0,riseChance:74,signal:'buy',reason:'실행 난이도 높고 목표 정렬도가 매우 높아 AI 적정가가 시장가보다 높게 산정됐어.',proofLog:['09:20 PRD 핵심 플로우 정리','18:40 MVP 기능명세 v5 확정'],fvHistory:[126,129,131,134,138,140,142],comments:[{tag:'매수중',name:'다원',text:'오늘 인증 퀄리티 좋다. 나 mock 매수 들어감.'},{tag:'응원',name:'민준',text:'창업 섹터 대장주 느낌 🚀'}]},
{name:'민준',ticker:'MJUN',goal:'운동 루틴',price:94,fv:88,chg:-3.2,emoji:'🏋️',color:'#16a34a',proofsToday:0,strikes:2,riseChance:38,signal:'risk',reason:'최근 인증 공백이 있어 FV가 점진 감쇠 중이야. 3-strike 중 2개가 쌓여 위험 신호가 켜졌어.',proofLog:['오늘 인증 없음 · 2일 연속 공백'],fvHistory:[98,97,95,92,90,89,88],comments:[{tag:'주의',name:'승화',text:'오늘은 짧게라도 인증하면 상폐 리스크 줄 듯.'}]},
{name:'다원',ticker:'DAWN',goal:'디자인 포트폴리오',price:117,fv:121,chg:5.1,emoji:'🎨',color:'#7c3aed',proofsToday:1,strikes:0,riseChance:68,signal:'buy',reason:'연속 작업 인증과 크루 평가가 좋아 시장가와 FV가 함께 상승 중이야.',proofLog:['16:10 랜딩페이지 시안 3장 업로드'],fvHistory:[109,111,112,116,117,119,121],comments:[{tag:'응원',name:'지후',text:'시안 발전 속도 미쳤다.'}]},
{name:'지후',ticker:'JHOO',goal:'시험 공부',price:83,fv:97,chg:1.4,emoji:'📚',color:'#f59e0b',proofsToday:1,strikes:1,riseChance:57,signal:'watch',reason:'목표 정렬도는 높지만 난이도 자기신고와 AI 기준선 차이가 있어 일부 보류됐어.',proofLog:['21:00 수학 오답노트 12문제'],fvHistory:[90,91,93,92,95,96,97],comments:[{tag:'응원',name:'승화',text:'오답노트면 FV 오를 만하지.'}]},
{name:'서윤',ticker:'SYUN',goal:'콘텐츠 업로드',price:76,fv:71,chg:-5.8,emoji:'🎬',color:'#0ea5e9',proofsToday:0,strikes:1,riseChance:31,signal:'risk',reason:'업로드 예고 후 결과 인증이 없어 시장 신뢰가 약해졌어. 오늘 인증 없으면 strike가 추가될 수 있어.',proofLog:['오늘 인증 없음 · 예고 공시만 존재'],fvHistory:[84,82,80,79,75,73,71],comments:[{tag:'주의',name:'다원',text:'예고보다 결과물이 필요해 보여.'}]}
];
let news=[
{type:'good',title:'[공시] 승화, 기능명세 v5 확정',body:'창업 프로젝트 섹터에 강한 호재. AI는 목표 정렬도 96점을 부여했다. 예상 FV +6.4%'},
{type:'bad',title:'[속보] 민준, 이틀 연속 운동 인증 누락',body:'체력 섹터 신뢰도 약화. 단, 폭락 대신 점진 감쇠 룰이 적용된다. 예상 FV -2.8%'},
{type:'neutral',title:'[분석] 다원, 포트폴리오 리뉴얼 예고',body:'TMI성 뉴스로 FV에는 미반영. 다만 크루 심리로 단기 시장가 변동 가능.'}
];
function krw(n){return '₩'+Math.round(n).toLocaleString('ko-KR')}
function pct(n){return `${n>=0?'+':''}${Number(n).toFixed(1)}%`}
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='home')renderHome();if(id==='news')renderNews();if(id==='leaderboard')renderRank();if(id==='proof')updateProofPreview();}
function startCrew(){state.crew=document.getElementById('crewNameInput').value||'바이브 크루';stocks[0].name=document.getElementById('myName').value||'승화';stocks[0].goal=document.getElementById('myGoal').value;document.getElementById('crewTitle').textContent=state.crew;go('home')}
function stockButton(s,i,rankLabel=''){return `<button class="stock-item" onclick="openStock(${i})"><div class="avatar" style="background:${s.color}">${rankLabel||s.emoji}</div><div class="stock-main"><b>${s.name} 주식</b><span>${s.ticker} · ${s.goal}</span></div><div class="stock-price"><b>${s.price.toFixed(0)}</b><span class="${s.chg>=0?'up':'down'}">${pct(s.chg)}</span></div></button>`}
function renderHome(){
 document.getElementById('crewTitle').textContent=state.crew;document.getElementById('cash').textContent=krw(state.cash);document.getElementById('portfolioValue').textContent=krw(state.portfolio);
 const avg=stocks.reduce((a,s)=>a+s.chg,0)/stocks.length;const proofs=stocks.reduce((a,s)=>a+s.proofsToday,0);const risks=stocks.filter(s=>s.strikes>0||s.signal==='risk').length;
 document.getElementById('avgChange').textContent=pct(avg);document.getElementById('activeProofs').textContent=`${proofs}건`;document.getElementById('riskCount').textContent=`${risks}명`;document.getElementById('marketMood').textContent=avg>=2?'강세장':avg>=0?'혼조세':'약세장';
 document.getElementById('headline').innerHTML=`${news[0].title}<br><span>${news[0].body}</span>`;
 const byUp=[...stocks].sort((a,b)=>b.chg-a.chg).slice(0,3);const byDown=[...stocks].sort((a,b)=>a.chg-b.chg).slice(0,3);
 document.getElementById('topGainers').innerHTML=byUp.map((s,r)=>stockButton(s,stocks.indexOf(s),r+1)).join('');
 document.getElementById('topLosers').innerHTML=byDown.map((s,r)=>stockButton(s,stocks.indexOf(s),r+1)).join('');
 const danger=byDown[0];document.getElementById('riskSummary').textContent=`${danger.name} ${danger.strikes}/3 strike · 오늘 인증이 없으면 FV 추가 감쇠 가능성이 있어.`;
 document.getElementById('stockList').innerHTML=stocks.map((s,i)=>stockButton(s,i)).join('')
}
function signalText(s){if(s.signal==='buy')return ['buy-signal','매수 추천','AI 적정가가 시장가보다 높고 인증 흐름이 좋아. 단, 실제 돈이 아닌 게임 판단이야.'];if(s.signal==='risk')return ['risk-signal','위험 신호','인증 공백/신뢰도 하락이 감지됐어. 매수보다 회복 인증 확인이 먼저야.'];return ['watch-signal','관망','상승 여지는 있지만 근거가 조금 부족해. 다음 인증 퀄리티를 보고 판단하자.']}
function openStock(i){state.selected=i;const s=stocks[i];document.getElementById('detailName').textContent=s.name+' 주식';document.getElementById('marketPrice').textContent=s.price.toFixed(0);document.getElementById('fvPrice').textContent=s.fv.toFixed(0);const gap=s.fv-s.price;const gapEl=document.getElementById('priceGap');gapEl.classList.toggle('negative',gap<0);gapEl.textContent=gap>=0?`AI 기준 ${gap.toFixed(0)} 저평가 · 매수 관심`:`AI 기준 ${Math.abs(gap).toFixed(0)} 고평가 · 관망 필요`;
 const [klass,title,desc]=signalText(s);document.getElementById('signalCard').innerHTML=`<span class="signal ${klass}">${title}</span><h3>${s.ticker} AI 투자 의견</h3><p>${desc}</p>`;
 document.getElementById('aiReason').innerHTML=`<h3>AI 판단 이유</h3><p>${s.reason}</p>`;document.getElementById('riseChance').textContent=`${s.riseChance}%`;document.getElementById('chanceNeedle').style.transform=`rotate(${(s.riseChance-50)*1.8}deg)`;
 document.getElementById('strikeDots').innerHTML=[0,1,2].map(n=>`<i class="${n<s.strikes?'on':''}"></i>`).join('');document.getElementById('strikeText').textContent=s.strikes>=3?'상장폐지 위험':s.strikes===2?'위험 임박':s.strikes===1?'주의':'안정';
 document.getElementById('proofCount').textContent=`${s.proofsToday}건`;document.getElementById('todayProofs').innerHTML=s.proofLog.map(p=>`<div><b>${p}</b><span>AI 신뢰도 반영 완료</span></div>`).join('');
 drawChart(s);renderComments();document.getElementById('betResult').textContent='';go('detail')}
function drawChart(s){const min=Math.min(...s.fvHistory)-4;const max=Math.max(...s.fvHistory)+4;const points=s.fvHistory.map((v,i)=>`${20+i*46},${130-((v-min)/(max-min))*100}`).join(' ');document.getElementById('chart').innerHTML=`<defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="${s.color}"/><stop offset="1" stop-color="#22c55e"/></linearGradient></defs><polyline points="${points}" fill="none" stroke="url(#g)" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><line x1="20" y1="${130-((s.fv-min)/(max-min))*100}" x2="300" y2="${130-((s.fv-min)/(max-min))*100}" stroke="#94a3b8" stroke-dasharray="6 6"/><text x="22" y="145" font-size="11" fill="#64748b">${s.fvHistory[0]}</text><text x="270" y="145" font-size="11" fill="#64748b">FV ${s.fv.toFixed(0)}</text>`}
function trade(type){const s=stocks[state.selected];const cost=s.price*10000;if(type==='buy'){state.cash-=cost;state.portfolio+=cost;s.price*=1.015;s.chg+=0.4}else{state.cash+=cost;state.portfolio-=cost;s.price*=0.985;s.chg-=0.4}openStock(state.selected)}
function bet(side){const s=stocks[state.selected];document.getElementById('betResult').textContent=`${s.name}의 내일을 ${side==='long'?'LONG':'SHORT'}으로 예측했어. 베팅금 5만원 mock 체결.`}
function selectCommentTag(tag){state.commentTag=tag;document.querySelectorAll('#commentTags button').forEach(b=>b.classList.toggle('active',b.dataset.tag===tag))}
function renderComments(){const s=stocks[state.selected];document.getElementById('commentList').innerHTML=s.comments.map(c=>`<div class="comment"><small>${c.tag}</small><b>${c.name}</b><p>${c.text}</p></div>`).join('')}
function addComment(){const input=document.getElementById('commentInput');const text=input.value.trim();if(!text)return;stocks[state.selected].comments.unshift({tag:state.commentTag,name:'나',text});input.value='';renderComments()}
function scoreRows(diff,imp,auth){return [['난이도',diff],['중요도',imp],['진정성',auth]].map(([name,val])=>`<div class="bar-row"><span>${name}</span><i style="--w:${val*20}%"></i><b>${val}/5</b></div>`).join('')}
function updateProofPreview(){const diff=+document.getElementById('difficulty').value;const imp=+document.getElementById('importance').value;const auth=+document.getElementById('authenticity').value;document.getElementById('diffLabel').textContent=diff;document.getElementById('impLabel').textContent=imp;document.getElementById('authLabel').textContent=auth;document.getElementById('scorePreview').innerHTML=scoreRows(diff,imp,auth)}
function submitProof(){const diff=+document.getElementById('difficulty').value;const imp=+document.getElementById('importance').value;const auth=+document.getElementById('authenticity').value;const score=diff*imp+auth*3;const impact=Math.min(14,(score/40*11)).toFixed(1);document.getElementById('proofResult').innerHTML=`<span class="muted">AI REVIEW</span><h3>심사 결과: 호재 +${impact}%</h3><p>난이도 ${diff}/5, 중요도 ${imp}/5, 진정성 ${auth}/5. 목표와 직접 연결된 인증이라 FV 상승률이 높게 잡혔어.</p><div class="score-bars">${scoreRows(diff,imp,auth)}</div>`;state.latestDisclosure={type:'good',title:'[공시] '+stocks[0].name+', 오늘 실적 인증 완료',body:`AI 심사 점수 ${score}/40. 난이도·중요도·진정성 기반 예상 FV +${impact}%.`};stocks[0].fv*=1+impact/100;stocks[0].fvHistory.push(Math.round(stocks[0].fv));stocks[0].fvHistory=stocks[0].fvHistory.slice(-7);stocks[0].chg+=Number(impact)/2;stocks[0].proofsToday+=1;stocks[0].proofLog.unshift('방금 제출한 실적 인증 · AI 호재 판정')}
function publishLatestNews(){if(!state.latestDisclosure){state.latestDisclosure={type:'neutral',title:'[예고] '+stocks[0].name+', 인증 공시 준비 중',body:'아직 제출된 AI 심사 결과가 없어 예고 공시로 등록됐다.'}}news.unshift(state.latestDisclosure);state.latestDisclosure=null;go('news')}
function renderNews(){document.getElementById('newsFeed').innerHTML=news.map(n=>`<article class="news-card"><span class="tag ${n.type}">${n.type==='good'?'호재':n.type==='bad'?'악재':'중립'}</span><h3>${n.title}</h3><p>${n.body}</p></article>`).join('')}
function renderRank(){const sorted=[...stocks].sort((a,b)=>b.chg-a.chg);document.getElementById('rankList').innerHTML=sorted.map((s,i)=>`<div class="stock-item"><div class="avatar" style="background:${s.color}">${i+1}</div><div class="stock-main"><b>${s.name}</b><span>${s.goal} · ${s.proofsToday} proofs</span></div><div class="stock-price"><b>${s.price.toFixed(0)}</b><span class="${s.chg>=0?'up':'down'}">${pct(s.chg)}</span></div></div>`).join('')}
renderHome();updateProofPreview();
